name: Build PKG Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x Fix\ Brother\ Printers\ for\ macOS27.app/Contents/MacOS/*

      - name: Build Component PKG
        run: |
          pkgbuild --component Fix\ Brother\ Printers\ for\ macOS27.app \
          --install-location /Applications \
          FixBrotherPrinters.pkg

      - name: Upload PKG Installer
        uses: actions/upload-artifact@v4
        with:
          name: FixBrotherPrinters-pkg
          path: FixBrotherPrinters.pkg
